project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - notebooks/*

format:
  html:
    css: styles.css
    theme: cosmo

website:
  title: "Learning Paths materials"
  search: false
  sidebar:
    style: "docked"
    contents:
      - href: notebooks/obstacles.qmd
        text: Obstacles
      - href: notebooks/methods.qmd
        text: Learning Methods
      - href: notebooks/correlations.qmd
        text: Correlations
      - href: notebooks/data_exploration.qmd
        text: Data Exploration
